### ISSUE TITLE
jefferson does not work with cstruct 1.4

### ISSUE THREAD

**Issue by ekuznetsov139** [sviehb/jefferson#9]
It looks like there were some internal API changes in cstruct, and, as a result, jefferson no longer works with the latest version:
```

[wd]>c:\python27\python.exe c:\Python27\Scripts\jefferson D04.jffs2 -d root
Traceback (most recent call last):
  File "c:\Python27\Scripts\jefferson", line 498, in <module>
    main()
  File "c:\Python27\Scripts\jefferson", line 470, in main
    fs_list = scan_fs(content, cstruct.BIG_ENDIAN, verbose=args.verbose)
  File "c:\Python27\Scripts\jefferson", line 290, in scan_fs
    unknown_node = Jffs2_unknown_node()
  File "c:\python27\lib\site-packages\cstruct\__init__.py", line 298, in __init__
    self.unpack(string)
  File "c:\Python27\Scripts\jefferson", line 71, in unpack
    cstruct.CStruct.unpack(self, data[:self.size])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I've reproduced the same behavior in Windows and in Ubuntu. 

It starts working if I manually install cstruct 1.0.

**Comment by davidgfnet** [comment]
Kudos man! Works as you say!

**Comment by bwbryant1** [comment]
Confirmed

**Comment by gjf** [comment]
Same for 1.8

**Comment by sviehb** [comment]
Thank you. Master works with `cstruct==1.8` (python3). Please let me know if you still encounter this issue.

**Comment by nusht** [comment]
not extracting 

jefferson 20000.jffs2
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/jefferson", line 4, in <module>
    __import__('pkg_resources').run_script('jefferson==0.4.1', 'jefferson')
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/jefferson-0.4.1-py3.10.egg/EGG-INFO/scripts/jefferson", line 10, in <module>
ModuleNotFoundError: No module named 'lzo'

**Comment by qkaiser** [comment]
@nusht please do not hijack closed issues to report unrelated problems. I recommend you open a new and dedicated issue for the problem you're encountering (which probably happens because you did not install required dependencies).
